---

common_extra_packages:
  - python-tox

flask_name: resume
flask_path: "/webapps/{{ flask_name }}"
flask_static_path: "{{ flask_project_path}}/pn/static"
flask_touch_reload_path: "{{ flask_path }}/.uwsgi_touch"
flask_requirements_file: "{{ flask_project_path }}/requirements.freeze"
flask_domain_name: "{{ host_public_domain_name }}"
flask_disallow_robots: no
flask_project_repo_url: https://github.com/ellmetha/morganaubert-resume.git
flask_ssl_only: yes
flask_env_variables:
  FLASK_CONFIG: production
  FLASK_INSTALL_PATH: "{{ flask_path }}"
flask_settings_pattern: jsonsettings
flask_jsonsettings_properties:
  SECRET_KEY: "{{ secret__flask_secret_key }}"
  GOOGLE_SITE_VERIFICATION_CODE: "{{ secret__google_site_verification_code }}"
